"""tags are now per user

Revision ID: 177bfcda0c0b
Revises: ae825d9f8367
Create Date: 2026-05-20 14:05:01.147832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "177bfcda0c0b"
down_revision: Union[str, Sequence[str], None] = "ae825d9f8367"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("tags_name_key"), "tags", type_="unique")
    op.create_unique_constraint("uq_user_tag_name", "tags", ["user_id", "name"])
    op.create_foreign_key(
        None, "tags", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.drop_constraint("uq_user_tag_name", "tags", type_="unique")
    op.create_unique_constraint(
        op.f("tags_name_key"), "tags", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("tags", "user_id")
    # ### end Alembic commands ###
